Fix package scripts

diff --git a/debian/preinst b/debian/preinst
--- a/debian/preinst
+++ b/debian/preinst
@@ -1,7 +1,6 @@
 #!/bin/bash -e
 
 NAME=buildbotics
-RUN_GROUP=$NAME
 ETC=/etc/$NAME
 
 case "$1" in
@@ -19,9 +18,19 @@ case "$1" in
         test -d $ETC || mkdir $ETC
 
         # Create group if it does not exist
-        if ! getent group $RUN_GROUP >/dev/null; then
-            echo -n "Adding system group $RUN_GROUP..."
-            if groupadd -r $RUN_GROUP 2>/dev/null; then
+        if ! getent group $NAME >/dev/null; then
+            echo -n "Adding system group $NAME..."
+            if groupadd -r $NAME 2>/dev/null; then
+                echo "done"
+            else
+                echo "failed"
+            fi
+        fi
+
+        # Create user if it does not exist
+        if ! getent passwd $NAME >/dev/null; then
+            echo -n "Adding system user $NAME..."
+            if useradd -r -g $NAME $NAME 2>/dev/null; then
                 echo "done"
             else
                 echo "failed"
